project:
  type: website
website:
  page-navigation: true
  title: "DHM"
  description: "Homepage for Dairy Health Management"
  site-url: "https://utrechtuniversity.github.io/DairyHealthManagement/"
  repo-url: https://github.com/UtrechtUniversity/DairyHealthManagement
  repo-actions: [edit, issue]
  open-graph: true
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Miel Hostens"
    background: "#FFCD00"
  sidebar:
    background: "#FFCD00"
    logo: "images/UtrechtUniversityLogo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/UtrechtUniversity/
        text: "GitHub organization"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Herd"
        contents:
          - href: herd-description.qmd
            text: Description
          - href: herd-tips-resources.qmd
            text: Tips + resources
      - section: "Weekly materials"
        contents:
          - href: weeks/reproduction-mgmt.qmd
            text: "Week 1"
          - href: weeks/transition-mgmt.qmd
            text: "Week 2"
          - href: weeks/youngstock-mgmt.qmd
            text: "Week 3"
          - href: weeks/infectious-disease-mgmt.qmd
            text: "Week 4"
          - href: weeks/udder-health-lameness-mgmt.qmd
            text: "Week 5"
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
freeze: auto
editor: visual