---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a peer teaching opportunity for everyone.

## Office hours

The entire teaching team is here to help you be successful in the course. You are encouraged to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so pass by during office hours. I encourage each and every one of you to take advantage of this resource! Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself. You can find a list of everyone's office hours [here](/course-team.html).

## Assesment

As you can see in the [course overview](/course-overview.html), each week starts with a knowledge challenge. This multiple choice questionaire is intended to challenge the knowledge we expect to be triggered during the current week. We don't see this as a formative test you need to pass but hopefully triggers you on gaps you might have within specific subjects. At the end of the week, a second multiple choice test will hopefully illustrate the progress you have made within the subject.

## Discussion forum

Have a question that might be valuable for all course participant? Prefer to write out your question in detail rather than asking in person? The online discussion forum is the best venue for these! We will use [github issue](https://github.com/Bovi-analytics/DairyHealthManagment/issues) as the online discussion forum. There is a chance another student has already asked a similar question, so please check the other posts before adding a new question. If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go here [github issue](https://github.com/Bovi-analytics/DairyHealthManagment/issues)), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.). For such matters, you may email Dr. Miel Hostens at [m.m.hostens\@uu.nl](mailto:m.m.hostens@uu.nl).

## Academic support

xxx

## Mental health and wellness

xxx

## **Technology accommodations**

xxx

## **Course materials costs**

There are no costs associated with this course. All readings will come from freely available, open resources (open-source textbooks, journal articles, etc.).

## **Assistance with Teams**

Teams will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.
