---
title: "Transition management"
subtitle: "Week 2"
editor: visual
---

# Introduction

The transition period is one of the most critical phases in a cow's life cycle. It encompassing the weeks before and after calving. Typically 3 weeks before until 3 weeks after, which is open for debate. This pivotal time prepares the cow's future lactation performance, health, and overall well-being.

Transition management is a multifaceted approach that involves understanding and addressing the unique physiological, nutritional, and environmental challenges faced by dairy cows during this period. From managing metabolic disorders to optimizing feed strategies and ensuring proper housing conditions, effective transition management is key to maximizing milk production, minimizing health issues, and promoting animal welfare.

Throughout this week, we will dive into transition management for dairy cows, have you explore the latest research findings, best practices, and practical strategies employed by dairy veterinarians. At the end of the week, you will present the transition management from your assigned herd to your peers.

## Learning goals

1.  The student is able to apply knowledge of the physiological changes occurring during the transition period in dairy cows to develop effective management strategies for optimizing cow health and productivity.

2.  The student utilizes principles of nutrition and feeding management to formulate balanced transition diets that meet the specific needs of dairy cows during the transition phase.

3.  The student can analyze common metabolic disorders associated with the transition period in dairy cows, and identify risk factors and potential interventions to mitigate their impact.

4.  Evaluate the influence of environmental factors, such as housing conditions and management practices, on the transition success of dairy cows, and propose strategies for optimizing the transition environment.

5.  The student evaluate the effectiveness of transition management practices using key performance indicators such as blood metabolites, milk production, and cow health outcomes.

6.  Critically assess research findings and industry recommendations related to transition management, discerning between evidence-based practices and anecdotal claims to make informed management decisions.

7.  Design comprehensive transition management plans tailored to the specific needs and resources of individual dairy farms, incorporating strategies for monitoring, adjusting, and optimizing transition protocols.

# Schedule

|             |                       Monday                        |                       Tuesday                        |                      Wednesday                       | Thursday |     Friday      |
|------------|:----------:|:----------:|:----------:|:----------:|:----------:|
| 9:00-9:45   |        [TR-KC](https://remindo.uu.nl//login)        | [TR-MTE-01](/classes/transition-mgmt/TR-MTE-01.html) |                                                      | TR-PR01  |   TR-PRES-01    |
| 10:00-10:45 |                                                     | [TR-MTE-02](/classes/transition-mgmt/TR-MTE-02.html) |                                                      | TR-PR01  |   TR-PRES-01    |
| 11:00-11:45 | [TR-IHC-01](classes/transition-mgmt/TR-IHC-01.html) |                                                      |                                                      | TR-PR02  |   TR-PRES-02    |
| 12:00-12:45 |                      TR-IHC-01                      |                                                      |                                                      | TR-PR02  |   TR-PRES-02    |
| 13:15-14:00 |                      TR-WC-03                       |  [TR-FNP-WC](/classes/transition-mgmt/TR-FNP.html)   | [TR-MTE-03](/classes/transition-mgmt/TR-MTE-03.html) |          |                 |
| 14:15-15:00 |                      TR-WC-03                       |                      TR-FNP-WC                       | [TR-MTE-04](/classes/transition-mgmt/TR-MTE-04.html) |          |                 |
| 15:15-16:00 |                                                     |                      TR-FNP-WC                       |                                                      |          |                 |
| 16:15-17:00 |                                                     |                      TR-FNP-WC                       |                                                      |          | TR-FNP DEADLINE |

## Knowledge challenge

Finish the [knowledge challenge](https://remindo.uu.nl//login) before the start of the first lecture.

## Prepare

📖 Read the [article](https://doi.org/10.3390/ani11020352) - *Monitoring and Improving the Metabolic Health of Dairy Cows during the Transition Period.*

📖 Read the [award article](https://doi.org/10.3168/jds.2022-23194) - *What makes for a good life for transition dairy cows?*

📖 Read the [symposium review](https://doi.org/10.3168/jds.2019-17271) - *Nutritional strategies to improve health, production and fertility.*

📖 Read the [review article](https://doi.org/10.1016/j.cvfa.2004.06.011) - *Behavioral needs of the transition cow and considerations for special needs facility design*.

## Participate

🖥️ [TR-IHC-01](/classes/transition-mgmt/tr-ihc-01.html) - From animal physiology towards transition monitoring

🖥️ TR-WC-03 - Basic economics on dairy farms

🖥️ [TR-MTE-01](/classes/transition-mgmt/tr-mte-01.html) - What makes for a good life for transition dairy cows

🖥️ TR-MTE-02 - Nutritional transition management in dairy cows

🖥️ TR-MTE-02 - Non-nutritional transition management in dairy cows

🖥️ TR-PR01

## Practice

📋 [Feed'n practice - Evaluate your transition cow feed strategy](/ae/ae-0-movies.html)

## Perform

✅ [Knowledge challenge](https://remindo.uu.nl//login)

📂 Present your herd's transition management strategy to your peers

⌨️ [Feed'n practice deadline week 2](/labs/lab-2.html)

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
