---
title: "Transition management"
subtitle: "Week 2"
editor: visual
---

# Introduction

Dairy cow transition management involves a strategic approach to ensure smooth physiological and metabolic shifts from the pre-partum to the post-partum period. Focused on optimizing health and milk production, it encompasses dietary adjustments, stress reduction, and monitoring to prevent issues like metabolic disorders and reduced fertility. Balancing nutrition, minimizing environmental stress, and offering appropriate evidence based veterinary care aids in the successful transition from late pregnancy to early lactation, benefiting both cow welfare and farm profitability. Effective transition management enhances milk yield, reproductive efficiency, and overall animal welfare in the critical phase of a dairy cow's life cycle.

## Learning goals

1.  The student acquires insight into the management of cows during the transition to lactation (e.g. (patho)-physiology, feeding strategies, housing).

2.  The student has insight into the processes (including economics) on the farm that relate to transition management and knows the effects of this on animal health, animal welfare, products and product quality (in relation to the requirements of the customers).

3.  The student acquires data-driven insights in animal health, animal welfare and products and product quality available on transition management. The student knows how these are recorded, and what their meaning and coherence is.

4.  The student acquires knowledge and understanding in transition management linked to clinical inspection.

5.  The student is able to create an animal health transition monitoring and treatment plan.

## Topics covered

-   ...

# Schedule

|             |  Monday   |   Tuesday    | Wednesday | Thursday |    Friday    |
|-------------|:---------:|:------------:|:---------:|:--------:|:------------:|
| 9:00-9:45   | KC 2 (WC) |              |           |          | PP 2.6 (WC)  |
| 10:00-10:45 |           |              |           |          | PP 2.6 (WC)  |
| 11:00-11:45 |  HC 2.1   |              |  IHC 2.4  |          | PP 2.6 (WC)  |
| 12:00-12:45 |  HC 2.1   |              |  IHC 2.4  |          | PP 2.6 (WC)  |
| 13:15-14:00 |  MTE 2.2  | FNP 2.3 (WC) |  MTE 2.5  |          |              |
| 14:15-15:00 |  MTE 2.2  | FNP 2.3 (WC) |  MTE 2.5  |          |              |
| 15:15-16:00 |           | FNP 2.3 (WC) |           |          |              |
| 16:15-17:00 |           | FNP 2.3 (WC) |           |          | FNP DEADLINE |

## Knowledge challenge

Finish the [knowledge challenge for week 2](https://forms.office.com/e/PpVW2HdWKx) before the start of the first lecture.

## Prepare

📖 Read the [symposium review](https://doi.org/10.3168/jds.2019-17271) article on *Nutritional strategies to improve health, production and fertility.*

📖 Read the [review article](https://doi.org/10.1016/j.cvfa.2004.06.011) on *Behavioral needs of the transition cow and considerations for special needs facility design*.

📖 Read the [award article](https://doi.org/10.3168/jds.2022-23194) on *What makes for a good life for transition dairy cows?*

## Participate

🖥️ IHC 2.1 - Transition management lecture

🖥️ MTE 2.2 - tbd

🖥️ IHC 2.4 - tbd

🖥️ IHC 2.4 - tbd

## Practice

📋 [Feed'n practice - Evaluate your transition cow feed strategy](/ae/ae-0-movies.html)

## Perform

✅ [Knowledge challenge week 2](https://forms.office.com/e/xw8hTUTctq)

📂 Present your herd's transition management strategy to your peers

⌨️ [Feed'n practice deadline week 2](/labs/lab-2.html)

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
