---
title: "Reproduction management"
subtitle: "Week 3"
editor: visual
---

# Introduction

Dairy cow reproduction management involves ...

## Learning goals

1.  ...

## Topics covered

-   ...

# Schedule

|             |   Monday    |   Tuesday    | Wednesday  | Thursday |    Friday    |
|-------------|:-----------:|:------------:|:----------:|:--------:|:------------:|
| 9:00-9:45   | KC 3.0 (WC) |              |            |          | PP 3.6 (WC)  |
| 10:00-10:45 |             |              |            |          | PP 3.6 (WC)  |
| 11:00-11:45 |   IHC 3.1   |              |  IHC 3.4   |          | PP 3.6 (WC)  |
| 12:00-12:45 |   IHC 3.1   |              |  IHC 3.4   |          | PP 3.6 (WC)  |
| 13:15-14:00 |   MTE 3.2   | FNP 3.3 (WC) |            |          |              |
| 14:15-15:00 |   MTE 3.2   | FNP 3.3 (WC) | WETLAB 3.5 |          |              |
| 15:15-16:00 |             | FNP 3.3 (WC) | WETLAB 3.5 |          |              |
| 16:15-17:00 |             | FNP 3.3 (WC) | WETLAB 3.5 |          | FNP DEADLINE |

## Prepare

📖Re-familiarize yourself with the bachelor course *BA Blok 18 voortplanting, BACO theorie*

📖 Supported resource - [Pathways to Pregnancy and Parturition (Senger, 2012)](https://books.google.com/books/about/Pathways_to_Pregnancy_Parturition.html?id=xZ55MAEACAAJ)

## Knowledge challenge

Finish the [Knowledge Challenge for week 3](https://forms.office.com/e/QauLM3wWtA) before the start of the first lecture.

## Participate

🖥️ IHC 3.1 - Reproduction physiology: oocyte to calf

🖥️ MTE 3.2 - Reproductive MGMT on dairy farms

🖥️ IHC 3.4 - Effect of metabolic and infectious disease on reproductive succes in dairy cows

## Practice

📋 [Feed'n practice 3.3 - lactating cow feed strategies](/ae/ae-0-movies.html)

📋 Wetlab 3.5 on cycle stage & pregnancy stage recognition

## Perform

✅ [Knowledge Challenge week 3.0](https://forms.office.com/e/QauLM3wWtA)

📂 Present your herd's reproduction management strategy to your peers 3.6

⌨️ [Feed'n practice deadline week 3](/labs/lab-2.html)

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
